# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0012_remove_s2_stuff_add_is_active_for_gyms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('endpoint', models.URLField(max_length=255)),
                ('auth', models.CharField(max_length=100)),
                ('p256dh', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionGym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('push_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='raidikalu.PushSubscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('push_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='raidikalu.PushSubscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='subscriptionpokemon',
            index=models.Index(fields=['name'], name='raidikalu_s_name_46e7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiongym',
            index=models.Index(fields=['name'], name='raidikalu_s_name_711e12_idx'),
        ),
    ]
