# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidikalu', '0013_add_push_subscription_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField()),
                ('push_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='raidikalu.PushSubscription')),
            ],
        ),
        migrations.AddIndex(
            model_name='subscriptiontier',
            index=models.Index(fields=['tier'], name='raidikalu_s_tier_d0279d_idx'),
        ),
    ]
